from packet import make_packet_parser
login_response_parser = make_packet_parser('\x69\x00', (
  ('length', 2),
  ('l_id1', 4),
  ('a_id', 4),
  ('l_id2', 4),
  ('_', 4),
  ('_', 24),
  ('_', 2),
  ('sex', 1),
  ('servers', (
    ('ip', 4),
    ('port', 2),
    ('name', 20),
    ('users', 2),
    ('_', 2),
    ('_', 2),
  )),
))
char_response_parser = make_packet_parser('\x6B\x00', (
  ('length', 2),
  ('slots_1', 1),
  ('slots_2', 1),
  ('slots_3', 1),
  ('_', 20),
  ('characters', (
    ('char_id', 4),
    ('base_exp', 4),
    ('zeny', 4),
    ('job_exp', 4),
    ('job_lvl', 4),
    ('_', 4),
    ('_', 4),
    ('option', 4),
    ('_', 4),
    ('_', 4),
    ('stat', 2),
    ('hp', 4),
    ('max_hp', 4),
    ('sp', 2),
    ('max_sp', 2),
    ('wspd', 2),
    ('class', 2),
    ('hair', 2),
    ('wep', 2),
    ('blvl', 2),
    ('sklpt', 2),
    ('hlmlow', 2),
    ('shld', 2),
    ('hlmtop', 2),
    ('hlmmid', 2),
    ('hair_clr', 2),
    ('cclr', 2),
    ('name', 24),
    ('str', 1),
    ('agi', 1),
    ('vit', 1),
    ('int', 1),
    ('dex', 1),
    ('luk', 1),
    ('slot', 2),
    ('rename', 2),
  )),
))
map_login_parser = make_packet_parser('\x71\x00', (
  ('char_id', 4),
  ('map_name', 16),
  ('ip', 4),
  ('port', 2),
))